services:
  alpinegateway:
    image: ghcr.io/hoeflechner/dockergateway:main
    container_name: alpinegateway
    restart: unless-stopped
    environment:
      - GATEWAY=192.168.22.11
      - CMD=sleep infinity
    cap_add:
      - NET_ADMIN
    dns:
      - 192.168.22.53
    networks:
      tor:
    build:
      context: .
      dockerfile: ./Dockerfile

networks:
  tor:
    external: true